spring:
  application:
    name: bank
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
  jpa:
    open-in-view: false
  mvc:
    format:
      date-time: iso

server:
  port: 8080
