create table person
(
    id         bigint generated by default as identity primary key,
    created_at timestamp    not null,
    login      varchar(255) not null unique
);

create table account
(
    id         bigint generated by default as identity primary key,
    created_at timestamp      not null,
    number     varchar(16)    not null unique,
    pin_code   varchar(255)   not null,
    balance    numeric(20, 2) not null,
    person_id  bigint         not null references person (id)
);

create table operation
(
    id         bigint generated by default as identity primary key,
    created_at timestamp      not null,
    type       varchar(255)   not null,
    amount     numeric(20, 2) not null,
    source_id  bigint references account (id),
    dest_id    bigint references account (id)
);
